# -----------------------------------------------------------------------------
# Copyright (c) 2014-2015 Leandro T. C. Melo (ltcmelo@gmail.com)
#
# This library is free software; you can redistribute it and/or
# modify it under the terms of the GNU Lesser General Public
# License as published by the Free Software Foundation; either
# version 2.1 of the License, or (at your option) any later version.
#
# This library is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public
# License along with this library; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301
# USA
# -----------------------------------------------------------------------------

# -------------------------- #
# --- The UaiSo! Project --- #
# -------------------------- #

import sys
import os.path


_file_header = (
    "/******************************************************************************\n"
    " * Copyright (c) 2014-2015 Leandro T. C. Melo (ltcmelo@gmail.com)\n"
    " *\n"
    " * This library is free software; you can redistribute it and/or\n"
    " * modify it under the terms of the GNU Lesser General Public\n"
    " * License as published by the Free Software Foundation; either\n"
    " * version 2.1 of the License, or (at your option) any later version.\n"
    " *\n"
    " * This library is distributed in the hope that it will be useful,\n"
    " * but WITHOUT ANY WARRANTY; without even the implied warranty of\n"
    " * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU\n"
    " * Lesser General Public License for more details.\n"
    " *\n"
    " * You should have received a copy of the GNU Lesser General Public\n"
    " * License along with this library; if not, write to the Free Software\n"
    " * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301\n"
    " * USA\n"
    " *****************************************************************************/\n"
    "\n"
    "/*---------------------------------------------*/\n"
    "/*---         The UaiSo! Project            ---*/\n"
    "/*---                                       ---*/\n"
    "/*--- This file is AUTOMATICALLY GENERATED. ---*/\n"
    "/*---  Do NOT edit, changes will be lost!   ---*/\n"
    "/*---  Refer to AstDefs.h for the details.  ---*/\n"
    "/*---------------------------------------------*/\n"
    "\n"
)


def write_file(casts_file, content):
    """ Write the AST casts file """

    print "Creating %s" % casts_file

    with open(casts_file, "w") as f:
        f.write(content)


def write_casts(ast_node, ast_kind):
    """ Write the casts """

    casts  = "#define %s%s_Cast(AST) static_cast<uaiso::%s%sAst*>(AST)\n" % (
        ast_node, ast_kind, ast_node, ast_kind)
    casts += "#define Const%s%s_Cast(AST) static_cast<const uaiso::%s%sAst*>(AST)\n" % (
        ast_node, ast_kind, ast_node, ast_kind)
    casts += "#define %s%sConst_Cast(AST) const_cast<uaiso::%s%sAst*>(%s%s_Cast(AST))\n" % (
        ast_node, ast_kind, ast_node, ast_kind, ast_node, ast_kind)
    return casts


def run():
    if len(sys.argv) != 1:
        print "Usage: python Scripts/GenAstCast.py"
        return

    contents = _file_header
    contents += (
        "#ifndef UAISO_ASTCASTS_H__\n"
        "#define UAISO_ASTCASTS_H__\n"
        "\n"
    )

    contents += write_casts("Expr", "");
    contents += write_casts("Spec", "");
    contents += write_casts("Name", "");
    contents += write_casts("Decl", "");
    contents += write_casts("Attr", "");
    contents += write_casts("Stmt", "");

    ast_kind = None
    defs_file = "Ast/AstDefs.h"
    with open(defs_file, "r") as f:
        for line in f:
            line = line.strip()

            if line.startswith("#define NAME_AST_MIXIN"):
                ast_kind = "Name"
                continue
            elif line.startswith("#define SPEC_AST_MIXIN"):
                ast_kind = "Spec"
                continue
            elif line.startswith("#define DECL_AST_MIXIN"):
                ast_kind = "Decl"
                continue
            elif line.startswith("#define EXPR_AST_MIXIN"):
                ast_kind = "Expr"
                continue
            elif line.startswith("#define STMT_AST_MIXIN"):
                ast_kind = "Stmt"
                continue
            elif line.startswith("#define ATTR_AST_MIXIN"):
                ast_kind = "Attr"
                continue
            elif not line.startswith("GEN_CODE_FOR"):
                ast_kind = None
                continue

            # We're in a GEN_CODE_FOR line: GEN_CODE_FOR(AstNode, AstBase)
            if ast_kind:
                # A bit of string processing to extract the `AstNode`.
                line = line[len("GEN_CODE_FOR") + 1 :]
                line = line.split(',')
                if not len(line) > 1:
                    print "Ast/AstDefs.h file got messed up"
                ast_node = line[0]

                contents += write_casts(ast_node, ast_kind)

    contents += (
        "\n"
        "#endif\n"
    )

    write_file("Ast/AstCast.h", contents)


if __name__ == "__main__":
    run()
