#!/usr/bin/python

# -----------------------------------------------------------------------------
# Copyright (c) 2014-2016 Leandro T. C. Melo (ltcmelo@gmail.com)
#
# This library is free software; you can redistribute it and/or
# modify it under the terms of the GNU Lesser General Public
# License as published by the Free Software Foundation; either
# version 2.1 of the License, or (at your option) any later version.
#
# This library is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public
# License along with this library; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301
# USA
# -----------------------------------------------------------------------------

# -------------------------- #
# --- The UaiSo! Project --- #
# -------------------------- #

import operator


def cpp_file_header():
    return (
        "/******************************************************************************\n"
        " * Copyright (c) 2014-2016 Leandro T. C. Melo (ltcmelo@gmail.com)\n"
        " *\n"
        " * This library is free software; you can redistribute it and/or\n"
        " * modify it under the terms of the GNU Lesser General Public\n"
        " * License as published by the Free Software Foundation; either\n"
        " * version 2.1 of the License, or (at your option) any later version.\n"
        " *\n"
        " * This library is distributed in the hope that it will be useful,\n"
        " * but WITHOUT ANY WARRANTY; without even the implied warranty of\n"
        " * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU\n"
        " * Lesser General Public License for more details.\n"
        " *\n"
        " * You should have received a copy of the GNU Lesser General Public\n"
        " * License along with this library; if not, write to the Free Software\n"
        " * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301\n"
        " * USA\n"
        " *****************************************************************************/\n"
        "\n"
        "/*---------------------------------------------*/\n"
        "/*---         The UaiSo! Project            ---*/\n"
        "/*---                                       ---*/\n"
        "/*--- This file is AUTOMATICALLY GENERATED. ---*/\n"
        "/*---  Do NOT edit, changes will be lost!   ---*/\n"
        "/*---  Refer to Tokens.def for new tokens.  ---*/\n"
        "/*---------------------------------------------*/\n"
        "\n")
